# Generated by Django 5.0.3 on 2024-03-31 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_name', models.CharField(max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prenoms', models.CharField(max_length=50)),
                ('nombre_depot', models.PositiveIntegerField(default=0)),
                ('numero_telephone', models.CharField(max_length=15)),
                ('localite', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=50)),
                ('numero_cni', models.CharField(max_length=50)),
                ('montant', models.PositiveIntegerField(default=0)),
                ('date', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='adherent_images/')),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=100)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ugacaci.collection')),
                ('ville', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ugacaci.ville')),
            ],
        ),
        migrations.CreateModel(
            name='CommissionClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='ugacaci.client')),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ugacaci.commission')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='CompteBancaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde_initial', models.PositiveIntegerField(default=0)),
                ('solde_actuel', models.PositiveIntegerField(default=0)),
                ('nb_depot', models.PositiveIntegerField(default=0)),
                ('date_ouverture', models.DateField(auto_now_add=True)),
                ('numero_compte', models.CharField(max_length=20, null=True, unique=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes_bancaires', to='ugacaci.client')),
            ],
        ),
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.PositiveIntegerField(default=0)),
                ('date_depot', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depots', to='ugacaci.client')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_operation', models.CharField(max_length=50)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_operation', models.DateTimeField(auto_now_add=True)),
                ('lieu_operation', models.CharField(default='Non spécifié', max_length=200)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ugacaci.comptebancaire')),
            ],
        ),
        migrations.CreateModel(
            name='Pret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_depot_eligible', models.PositiveIntegerField(default=0)),
                ('duree', models.PositiveIntegerField(default=3)),
                ('date_pret', models.DateTimeField(auto_now=True)),
                ('montant_pret', models.PositiveIntegerField()),
                ('montant_remboursement', models.PositiveIntegerField()),
                ('date_limite_remboursement', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prets', to='ugacaci.client')),
            ],
        ),
    ]
