# Generated by Django 5.0.3 on 2024-04-02 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugacaci', '0002_pretbancaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='pretbancaire',
            name='montant_rembourssement',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
