# Generated by Django 5.0.3 on 2024-04-02 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugacaci', '0003_pretbancaire_montant_rembourssement'),
    ]

    operations = [
        migrations.AddField(
            model_name='pretbancaire',
            name='date_naissance',
            field=models.DateField(null=True),
        ),
    ]
