# Generated by Django 5.0.3 on 2024-04-02 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugacaci', '0004_pretbancaire_date_naissance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pretbancaire',
            old_name='date_naissance',
            new_name='date_rembourssement',
        ),
        migrations.AddField(
            model_name='pretbancaire',
            name='lieu_demande',
            field=models.CharField(max_length=26, null=True),
        ),
    ]
