# Generated by Django 5.0.3 on 2024-04-02 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugacaci', '0006_rename_date_rembourssement_pretbancaire_date_remb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pretbancaire',
            name='date_demande',
            field=models.DateTimeField(null=True),
        ),
    ]
