# Generated by Django 5.0.3 on 2024-04-02 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugacaci', '0007_alter_pretbancaire_date_demande'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pretbancaire',
            old_name='date_remb',
            new_name='date_rembourssement',
        ),
    ]
