# Generated by Django 5.0.3 on 2024-04-02 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugacaci', '0008_rename_date_remb_pretbancaire_date_rembourssement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pretbancaire',
            name='date_demande',
            field=models.DateField(null=True),
        ),
    ]
