# Generated by Django 5.0.3 on 2024-04-03 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugacaci', '0010_rename_date_rembourssement_pretbancaire_date_remboursement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pretbancaire',
            old_name='date_remboursement',
            new_name='date_rembourssement',
        ),
    ]
