# Generated by Django 5.0.3 on 2024-04-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugacaci', '0011_rename_date_remboursement_pretbancaire_date_rembourssement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pretbancaire',
            name='montant_demande',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pretbancaire',
            name='montant_rembourssement',
            field=models.IntegerField(null=True),
        ),
    ]
